// Generated by typings
// Source: https://raw.githubusercontent.com/meteor-typings/alanning-roles/9960894dba03dbaf0b2a03986ed8d041e6d629e0/main.d.ts
interface RolesDAO {
  _id?: string;
  name?: string;
}

declare module Roles {
  function createRole(roleName: string): string;
  function deleteRole(roleName: string): void;
  function addUsersToRoles(users: any, roles: any, groups?: string): void;
  function removeUsersFromRoles(users: any, roles: any): void;
   // User can be user ID or user object.
  function userIsInRole(user: any, roles: any): boolean;
  function getRolesForUser(userId: string): string[];
  function getAllRoles(): Mongo.Cursor<RolesDAO>;
  function getUsersInRole(roleName: string): Mongo.Cursor<RolesDAO>;
  var GLOBAL_GROUP: string;
}
